services:
  nextjs:
    build: .
    container_name: gestion-gastos-nextjs
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - proxy

networks:
  proxy:
    external: true
